default:
  logs_loc: "\\Office for National Statistics\\Best Practice Assurance and Improvement - E-learning metrics\\1.E-learning_logs"
  staff_counts_loc: "\\Office for National Statistics\\People Analytics - Monthly Outputs for Reggie\\Staffcounts\\2023-2024"
  outputs_loc: "\\Office for National Statistics\\Best Practice Assurance and Improvement - E-learning metrics\\2.Exports\\HD_testing\\"
  date: "2023-09-30"
